version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fractal_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: fractal_tasks
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- NEW SECTION ---
  server:
    build: ./server
    container_name: fractal_server
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: fractal_tasks
    depends_on:
      - db
  client:
    build: ./client
    container_name: fractal_client
    ports:
      - "3000:3000"
    stdin_open: true # Needed for React interactive mode
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
